import { z } from "zod";

// ==========================================
// 1. ZSCALER RAW LOG PARSING SCHEMA
// Ensures the CSV parser outputs exactly what we expect
// ==========================================
export const ZScalerLogSchema = z.object({
  id: z.string().uuid().optional(), // Generated by backend during parse
  timestamp: z.string(), // e.g., "Mon Jun 20 15:29:11 2022"
  user: z.string(), // e.g., "new-gre"
  protocol: z.string(), // e.g., "HTTP"
  action: z.enum(["Allowed", "Blocked", "Caution", "None"]).catch("None"),
  url: z.string(),
  app: z.string(),
  category: z.string(),
  clientIp: z.string(),
  serverIp: z.string(),
  requestMethod: z.string(),
  responseCode: z.string(),
  userAgent: z.string(),
  sentBytes: z.coerce.number(), // Zod forces string to number
  receivedBytes: z.coerce.number(),
  threatName: z.string().default("None"),
  ruleLabel: z.string().default("None"),
  rawLine: z.string(), // MUST keep the original CSV string
});

export type ZScalerLogEntry = z.infer<typeof ZScalerLogSchema>;

// ==========================================
// 2. TIMELINE EVENT SCHEMA (GEMINI FLASH OUTPUT)
// The summarized "Story" of the log file
// ==========================================
export const TimelineEventSchema = z.object({
  timestamp: z.string(),
  title: z.string(),
  description: z.string(),
  isAnomaly: z.boolean(),
});

export type TimelineEvent = z.infer<typeof TimelineEventSchema>;

// ==========================================
// 3. ANOMALY SCHEMA (DEEPSEEK-R1 OUTPUT)
// The deep forensic reasoning for flagged events
// ==========================================
export const AnomalyDetailSchema = z.object({
  logId: z.string().optional(), // Reference to the parsed log line
  timestamp: z.string(),
  action: z.string(),
  url: z.string(),
  clientIp: z.string(),
  rawLine: z.string(), // Critical for SOC pivoting
  reasoning: z.string(), // The DeepSeek 'Thought' process
  confidenceScore: z.number().min(0).max(1), // Normalized to 0.0 - 1.0
  severity: z.enum(["Critical", "High", "Medium", "Low"]),
});

export type AnomalyDetail = z.infer<typeof AnomalyDetailSchema>;

// ==========================================
// 4. DATABASE DOCUMENT SCHEMA (SQLITE / SYSTEM)
// How we track the file upload and processing state
// ==========================================
export const LogUploadJobSchema = z.object({
  id: z.string(),
  filename: z.string(),
  fileHash: z.string(), // Used for deduplication
  uploadDate: z.date(),
  status: z.enum(["pending", "processing", "completed", "failed"]),
  summary: z.string().optional(), // Gemini's executive summary
  timeline: z.array(TimelineEventSchema).default([]),
  anomalies: z.array(AnomalyDetailSchema).default([]),
});

export type LogUploadJob = z.infer<typeof LogUploadJobSchema>;
